version: "3.7"

services:
  adguard:
    image: adguard/adguardhome
    container_name: dns
    healthcheck:
      test: nslookup example.org 127.0.0.1 || exit 1
    restart: unless-stopped
    networks:
      traefik0:
    ports:
      - 53:53/tcp
      - 53:53/udp
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ${FAST}/configs/adguardhome:/opt/adguardhome/conf
      - ${STORAGE}/adguardhome:/opt/adguardhome/work
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.services.adguard.loadbalancer.server.port: 80

networks:
  traefik0:
    external: true
