version: "3.7"

services:
  adguard:
    image: adguard/adguardhome:v0.106.3
    container_name: dns
    healthcheck:
      test: nslookup example.org 127.0.0.1 || exit 1
    restart: unless-stopped
    networks:
      traefik0:
    ports:
      - 53:53/tcp
      - 53:53/udp
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ${FAST}/configs/adguardhome:/opt/adguardhome/conf
      - ${STORAGE}/adguardhome:/opt/adguardhome/work
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.services.adguard.loadbalancer.server.port: 80

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      traefik0:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${FAST}/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
  
  gateway:
    image: jwilder/whoami
    container_name: gateway
    restart: unless-stopped
    networks:
      traefik0:
    environment:
    - VIRTUAL_HOST=wh.${DOMAIN}

  cloudflared:
    image: cloudflare/cloudflared:2022.1.3
    container_name: cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - --hostname
      - wh.${DOMAIN}
      - --url
      - http://nginx-proxy:80
      - --http-host-header
      - wh.${DOMAIN}
      - --name
      - wh
      - --overwrite-dns
    networks:
      traefik0:
    volumes:
      - ${FAST}/cloudflared:/etc/cloudflared

networks:
  traefik0:
    external: true
