version: "3.7"

networks:
  traefik0:
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2021-10-23T03-28-24Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
      MINIO_BROWSER_REDIRECT_URL: https://minio.${DOMAIN}
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    networks:
      - traefik0
    volumes:
      - ${STORAGE}/minio/data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.minio-https.service: minio
      traefik.http.routers.minio-https.entrypoints: websecure
      traefik.http.routers.minio-https.rule: Host(`minio.${DOMAIN}`)
      traefik.http.services.minio.loadbalancer.server.port: "9000"
      traefik.http.services.minio-console.loadbalancer.server.port: "9001"
      traefik.http.routers.minio-console-https.service: minio-console
      traefik.http.routers.minio-console-https.entrypoints: websecure
      traefik.http.routers.minio-console-https.rule: Host(`mcon.${DOMAIN}`)